
const D=window.APP_DATA,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY='pm-interview-v2';let S=JSON.parse(localStorage.getItem(KEY)||'{"q":{},"m":{},"theme":"light"}'),cur=null,installPrompt=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){localStorage.setItem(KEY,JSON.stringify(S));progress()}function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1400)}
function show(id){if(id!=='home'&&id!=='learn')history.replaceState(null,'','#'+id);$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active');$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));$('#mobileTitle').textContent=id==='home'?'Разделы':id==='trainer'?'Тренажёр':id==='glossary'?'Термины':'Настройки';closeMenu();scrollTo(0,0)}
function nav(){let n=$('#nav');n.innerHTML='';const target=D.modules.find(m=>m.id==='mexico_job');if(target){n.insertAdjacentHTML('beforeend','<div class="nav-title">Целевая вакансия</div>');addNav(target.title,target.id)}const kb=['research_toolkit','research_playbook','geo_playbook_full','product_frameworks','product_discovery','product_delivery','product_thinking'];n.insertAdjacentHTML('beforeend','<div class="nav-title">Product Knowledge Base</div>');kb.map(id=>D.modules.find(m=>m.id===id)).filter(Boolean).forEach(m=>addNav(m.title,m.id));n.insertAdjacentHTML('beforeend','<div class="nav-title">Исходные материалы</div>');D.modules.filter(m=>m.id!=='mexico_job'&&!kb.includes(m.id)).forEach(m=>addNav(m.title,m.id));n.insertAdjacentHTML('beforeend','<div class="nav-title">Практика</div>');addNav('Тренажёр','trainer');addNav('Термины','glossary');addNav('Настройки','settings')}
function addNav(t,id){let b=document.createElement('button');b.textContent=t;b.dataset.go=id;b.onclick=()=>D.modules.some(m=>m.id===id)?openModule(id):show(id);$('#nav').appendChild(b)}
function renderModules(q=''){q=q.toLowerCase().trim();$('#moduleList').innerHTML=D.modules.filter(m=>!q||(m.title+' '+m.stages.map(s=>s.title+' '+s.summary+' '+(s.terms||[]).join(' ')).join(' ')).toLowerCase().includes(q)).map(m=>`<article class="module-row" data-mid="${m.id}"><div class="micon">${m.icon}</div><div><h3>${esc(m.title)}</h3><p>${m.stages.length} блоков · каскад сверху вниз</p></div><div class="meta ${S.m[m.id]?'done':''}">${S.m[m.id]?'✓ изучено':'открыть →'}</div></article>`).join('');$$('.module-row').forEach(x=>x.onclick=()=>openModule(x.dataset.mid))}
function ul(items){return items&&items.length?`<ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>Отдельных пунктов в источнике нет.</p>'}
function openModule(id){cur=D.modules.find(m=>m.id===id);history.replaceState(null,'','#'+id);show('learn');$('#mobileTitle').textContent=cur.title;$('#mark').textContent=S.m[id]?'✓ Изучено':'✓ Отметить изученным';let html=`<div class="module-head"><div class="eyebrow">${esc(cur.source||'')}</div><h1>${cur.icon} ${esc(cur.title)}</h1><p>${cur.special==='funnel'?'Путь пользователя разбит на последовательные этапы. Каждый этап раскрывается по одной логике.':'Все исходные блоки сохранены и расположены сверху вниз. Каждый блок раскрывается отдельно.'}</p></div><div class="cascade">`;cur.stages.forEach((s,i)=>{if(cur.special==='funnel'){html+=`<article class="stage-card"><div class="stage-head"><div class="stage-num">${i+1}</div><div><h2>${esc(s.title)}</h2><p>${esc(s.summary)}</p></div></div><details class="accordion"><summary>Схема и смысл этапа</summary><div class="accbody">${esc(s.schema||s.summary)}</div></details><details class="accordion"><summary>Термины</summary><div class="accbody"><div class="termchips">${(s.terms||[]).map(t=>`<span class="termchip">${esc(t)}</span>`).join('')||'—'}</div></div></details><details class="accordion"><summary>Потенциальные проблемы</summary><div class="accbody">${ul(s.problems)}</div></details><details class="accordion"><summary>Как диагностировать</summary><div class="accbody">${ul(s.diagnostics)}</div></details><details class="accordion"><summary>Возможная оптимизация</summary><div class="accbody">${ul(s.optimization)}</div></details><details class="accordion"><summary>Что проверить после изменения</summary><div class="accbody">${ul(s.after)}</div></details></article>`}else{html+=`<article class="stage-card"><div class="stage-head"><div class="stage-num">${i+1}</div><div><h2>${esc(s.title)}</h2><p>${esc(s.summary||'Разверни блок для полного материала.')}</p></div></div><details class="accordion"><summary>Схема / полный материал</summary><div class="accbody sourcebody">${s.body}</div></details><details class="accordion"><summary>Термины этого блока</summary><div class="accbody"><div class="termchips">${(s.terms||[]).map(t=>`<span class="termchip">${esc(t)}</span>`).join('')||'Основные определения находятся в полном материале и словаре.'}</div></div></details><details class="accordion"><summary>Как применять на интервью</summary><div class="accbody"><p><b>Логика:</b> объясни смысл блока → назови ключевые метрики/термины → покажи риск или trade-off → объясни, как проверишь решение данными.</p></div></details></article>`}});html+='</div>';$('#learnBody').innerHTML=html}
function progress(){let k=Object.values(S.q).filter(x=>x==='known').length,r=Object.values(S.q).filter(x=>x==='review').length,md=Object.values(S.m).filter(Boolean).length,total=D.questions.length+D.modules.length,p=Math.round((k+md)/total*100);$('#pct').textContent=$('#mpct').textContent=p+'%';$('#bar').style.width=p+'%';$('#progressText').textContent=`${k} вопросов знаю · ${r} повторить · ${md} разделов изучено`;$('#known').textContent=k}
function qcats(){[...new Set(D.questions.map(x=>x.cat))].sort().forEach(c=>$('#qcat').insertAdjacentHTML('beforeend',`<option>${esc(c)}</option>`))}
function renderQ(){let q=$('#qsearch').value.toLowerCase().trim(),cat=$('#qcat').value,only=$('#review').classList.contains('active');let arr=D.questions.map((x,i)=>({...x,i})).filter(x=>(cat==='ALL'||x.cat===cat)&&(!q||(x.q+' '+x.a).toLowerCase().includes(q))&&(!only||S.q[x.i]==='review'));$('#qlist').innerHTML=arr.map((x,n)=>`<article class="question"><div class="qtop"><div class="qnum">${n+1}</div><div class="qmain"><b>${esc(x.q)}</b><small>${esc(x.cat)}</small></div><div class="qstatus"><button class="known ${S.q[x.i]==='known'?'on':''}" data-i="${x.i}" data-v="known">Знаю</button><button class="review ${S.q[x.i]==='review'?'on':''}" data-i="${x.i}" data-v="review">Повторить</button></div></div><details><summary>Показать ответ</summary><div class="answer">${esc(x.a)}</div></details></article>`).join('');$$('.qstatus button').forEach(b=>b.onclick=()=>{S.q[b.dataset.i]=S.q[b.dataset.i]===b.dataset.v?'':b.dataset.v;save();renderQ()})}
function renderG(){let q=$('#gsearch').value.toLowerCase().trim();$('#glist').innerHTML=D.glossary.filter(x=>!q||(x.term+' '+x.def).toLowerCase().includes(q)).map(x=>`<article class="gloss"><b>${esc(x.term)}</b><span>${esc(x.def)}</span></article>`).join('')}
function openMenu(){$('#sidebar').classList.add('open');$('#scrim').classList.add('show')}function closeMenu(){$('#sidebar').classList.remove('open');$('#scrim').classList.remove('show')}
function init(){
try{
nav();qcats();renderQ();renderG();progress();document.documentElement.dataset.theme=S.theme||'light';$$('[data-go]').forEach(b=>b.onclick=()=>{const id=b.dataset.go;D.modules.some(m=>m.id===id)?openModule(id):show(id)});$('#qsearch').oninput=renderQ;$('#qcat').onchange=renderQ;$('#review').onclick=e=>{e.currentTarget.classList.toggle('active');renderQ()};$('#gsearch').oninput=renderG;$('#mark').onclick=()=>{if(!cur)return;S.m[cur.id]=!S.m[cur.id];save();$('#mark').textContent=S.m[cur.id]?'✓ Изучено':'✓ Отметить изученным';toast(S.m[cur.id]?'Раздел изучен':'Отметка снята')};$('#theme').onclick=()=>{S.theme=S.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=S.theme;save()};$('#menu').onclick=openMenu;$('#scrim').onclick=closeMenu;$('#export').onclick=()=>{let b=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='pm-interview-progress.json';a.click();URL.revokeObjectURL(a.href)};$('#import').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{S=JSON.parse(r.result);save();renderModules();renderQ();renderG();toast('Импортировано')}catch{toast('Ошибка файла')}};r.readAsText(f)};$('#reset').onclick=()=>{if(confirm('Сбросить прогресс?')){S={q:{},m:{},theme:S.theme};save();renderQ()}};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false});$('#install').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#install').hidden=true}};if(location.hash){
 const wanted=location.hash.slice(1);
 if(D.modules.some(m=>m.id===wanted)) openModule(wanted);
 else if(['trainer','glossary','settings'].includes(wanted)) show(wanted);
 else if(D.modules[0]) openModule(D.modules[0].id);
}else if(D.modules[0]) openModule(D.modules[0].id);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
document.documentElement.dataset.appReady='1';
}catch(err){
 console.error(err);
 const box=document.getElementById('bootError');
 if(box){box.hidden=false;box.textContent='Ошибка запуска приложения: '+(err?.message||err)}
}
}init();
